[theme]
primaryColor = "#F97316"
backgroundColor = "#FFF7ED"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#431407"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
